### ISSUE TITLE
Error when calling insertPackage: permission issue ? 

### ISSUE THREAD

**Issue by kabarigou** [eddelbuettel/drat#114]
Hello,

Thanks for this great package.

After forking the drat repository, cloning the folder locally, when I try to insert a binary windows R package into drat, I get the following error (under Windows): 
```R
> drat::insertPackage(file="StanMoMo-win.zip", repodir="./drat")
Error in read.dcf(path, "Built") : cannot open the connection
In addition: Warning message:
In read.dcf(path, "Built") :
  cannot open compressed file 'C:\Users\KARIMB~1\AppData\Local\Temp\RtmpiUbONP/StanMoMo-win.zip/DESCRIPTION', probable reason 'No such file or directory'
```
For information, my working directory and temporary file are
```R
> getwd()
[1] "C:/Users/Karim Barigou/Dropbox/Package StanMoMo"
> tempfile()
[1] "C:\\Users\\KARIMB~1\\AppData\\Local\\Temp\\RtmpiUbONP\\file3fc017d6e3f"
```
I don't know how I can solve this. Is it a permission issue ? I tried to run R as administrator but I still get the same error.
It seems that the function is searching for the file **in the temporary directory not in the working directory**.
I tried under Mac and got the same kind of error:
```R
> drat::insertPackage(file="StanMoMo-win.zip", repodir="./drat")
Error in read.dcf(path, "Built") : cannot open the connection
In addition: Warning message:
In read.dcf(path, "Built") :
  cannot open compressed file '/var/folders/7c/5xb6gq6d739b_rs0hm2d2_w00000gn/T//RtmphkVdLN/StanMoMo-win.zip/DESCRIPTION', probable reason 'No such file or directory'

```

For information: 

- I use the `drat` version 0.1.8.1 installed via 
```R
remotes::install_github("eddelbuettel/drat")
```

- I have forked the `drat-base/drat ` repository from https://github.com/drat-base/drat 

Any help is much appreciated,
Thank you very much in advance.

**Comment by eddelbuettel** [comment]
Hi there and glad you like it. (We're in the middle of a small update switching to also enabling serving GitHub Pages from the `docs/` folder so documentation and code may be a little out of sync.  Please edit your question and add a) which `drat` version you use and where you installed it from, and b) how you bootstrapped you `drat` repo: fork of which repo, or `dratInit()` or ...)

That looks like a permissions issue indeed, and as I longer use windows I am not in the best position to offer tips. I presume
paths like `C:\Users\KARIMB~1\AppData\Local\Temp\RtmpO09aLu` are what you see when you call `tempfile()` in R on your machine?

If that is your normal temp.file, why would it refuse to let you open and unpack the package source so that `drat` can read the `DESCRIPTION` file.  That is a little odd.

**Comment by kabarigou** [comment]
Thank you for the quick reply! I have updated my question with some additional information.

**Comment by eddelbuettel** [comment]
It looks like a logic error I may have made but I am not seeing it.  Both for Windows and on the mac, we construct a path ... which then does not exist.

The simplest answer may have to do with 0.1.8.1 and the "in-progress" changes I made (and that @RomanHornung and I are working on some documentation for)  which has to do with using `docs/` rather than `gh-pages` -- so please try `options(dratBranch="docs") ` (and/or set `location="docs/" when you call `insertPackage`).    This _may_ just be it.

Otherwise I'd be stumped.  Can you maybe help debug a local copy of `drat` at your end (the old way via `print` is what I often do, or `browser()` or other R tricks to debug?

**Comment by kabarigou** [comment]
Thank you for the quick reply! 

Problem solved! In fact, I produced the binaries via Github Actions. This produces zip files containing the binary windows zip file and the binary Mac gz file. What I was trying to do was inserting the zip file containg the binary, not the binary itself. 

To be more explicit, Github Actions produces 

- `windows-latest-release.zip` containing `StanMoMo_1.0.0.zip`
- `macOS-latest-release.zip` containing `StanMoMo_1.0.0.gz` 

I was calling the function `drat::insertPackage` on `windows-latest-release.zip` rather than `StanMoMo_1.0.0.zip`...

I have just called `drat::insertPackage` on `StanMoMo_1.0.0.zip` and `StanMoMo_1.0.0.gz` and the binaries were included perfectly, as expected.

Maybe for future development of the package, it could be interesting to include drat in the Github Actions Workflow. At the moment, Github Actions allows the user to build binaries every time there is a Github push. Is it possible to update the binaries in the drat folder every time there is a push in a given repository ? I don't know.

**Comment by eddelbuettel** [comment]
Yay!  Very nice. 

In favour of GitHub Actions too -- I use them quite a bit, I personally do not bother so much with artifact creation and storage but other people.  As ... this seems to be your itch to scratch, do you want to maybe start by putting some bullet points together and what is there, what is missing, how we could get there etc pp?  Maybe it is "just" a need for more documentation and walkthrough (as I am currently writing one along with @RomanHornung) ?

**Comment by kabarigou** [comment]
I would be happy to help improve the documentation. Below you can find a first draft 😉 

Hereafter are **the main steps to build binary packages via Github Actions for Windows and Mac and insert them into a drat repository**. For the rest, I only assume that the repository package is a standard github repository. 

1. If this is the first time you use the CI Github Workflow, one can call 
```R
usethis::use_github_action("check-release")
```
to initialize Continuous Integration in the Github repository. From now on, the R package will be checked for every push.
2. Create the following yaml file in `.github/workflows/`. This will build Windows, Mac and Ubuntu binaries of your package for every push and pull request (the file can be simplified if Ubuntu is not required or if the binaries should not be built for every push).
```yaml
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Package builder

jobs:
  binary:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.package_repo }}
          ref: ${{ github.event.inputs.package_branch }}

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "16.04"))')
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran(c("rcmdcheck", "caret", "gbm", "randomForest", "e1071"))
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Build source package
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          src <- pkgbuild::build(".", dest_path = tempdir(), vignettes = FALSE, manual = FALSE)
          dir.create("build")
          file.copy(src, "build")
        shell: Rscript {0}

      - name: Build binary
        if: matrix.config.os != 'ubuntu-latest'
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          bin <- pkgbuild::build(".", dest_path = tempdir(), vignettes = FALSE, manual = FALSE, binary = TRUE)
          dir.create("build_bin")
          file.copy(c(bin), "build_bin")
        shell: Rscript {0}

      - name: Upload source package
        if: matrix.config.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}
          path: build/

      - name: Upload binary packages
        if: matrix.config.os != 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}
          path: build_bin/
```

3. If the construction of binaries is successful, you should get three artifacts which look like this:
![artifacts](https://user-images.githubusercontent.com/65466182/113518498-03189b80-9587-11eb-98d4-225d5d2378aa.png)
4. Download the zip artifacts and **make sure that you unzip the zip artifacts after download.**
5. After unzipping, you should normally get two binaries of the form: `nameofpackage_VersionNumber.zip` (for Windows) and `nameofpackage_VersionNumber.tgz` (for Mac)
6. Now, you can proceed by following the [standard vignette](https://eddelbuettel.github.io/drat/vignettes/dratforauthors/) of `drat`. For instance, assuming that your `drat` repository is in your working directory with your binaries, you can simply call:
```R
drat::insertPackage(file="nameofpackage_VersionNumber.zip", repodir="./drat")
drat::insertPackage(file="nameofpackage_VersionNumber.tgz", repodir="./drat")
```
7. Your drat repository should be updated. Now, you just need to commit and push, that's it! 

Hope it helps!
